# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       obs-service-repo

# >> macros
# << macros

Summary:    Repo service designed for droid-hal-device builds
Version:    0.1
Release:    1
Group:      Development/Tools
License:    GPLv2
URL:        https://git.merproject.org/mer-obs/obs-repo-service
Source0:    %{name}-%{version}.tar.bz2
Source100:  obs-service-repo.yaml
Requires:   obs-source_service
Requires:   git-core
Requires:   python

%description
%{summary}.

%prep
%setup -q -n src

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/usr/lib/obs/service/
cp repo %{buildroot}/usr/lib/obs/service/
cp repo.service %{buildroot}/usr/lib/obs/service/

mkdir -p %{buildroot}/%{_bindir}
cp repo.py %{buildroot}/%{_bindir}/repo
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
/usr/lib/obs/
%defattr(755,root,root,-)
/usr/lib/obs/service/repo
%{_bindir}/repo
# >> files
# << files
