#!/bin/sh

find /srv/service/.cache -type f -mtime +180 -print0 |xargs -0 rm

cd /data/service
for i in `ls -1 |grep -v ^repo$`; do
  (cd $i && repo sync --no-clone-bundle --fetch-submodules -j1)
done

